Repository acm-uic/sparkhacks-2023, pull requests merged in 2022-10, with the labels that each got.

#30 Updating the @mention to actually link to a user profile on Github
  README.md
Labels: bug, documentation

#32 Added my name to contributors
  README.md
Labels: documentation, good first issue

#34 Changed the formatting of the contributors section to have a line in between each name so it doesn't look weird
  README.md
Labels: documentation

#31 Update README.md
  README.md
Labels: documentation, good first issue
